services:
 mongo:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_data_container:/data/db
 mongo2:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_data_container2:/data/db
    
 mysql:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_data_container:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 consumption-service:
  depends_on:
    - mongo
  image: r0811509/mobile-consumption
  ports:
    - 8052:8052
  links:
    - mongo
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo
   
 user-service:
  depends_on:
    - mongo2
  image: r0811509/mobile-user
  ports:
    - 8053:8053
  links:
    - mongo2
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo2
   
 beer-service:
  depends_on:
    - mysql
  image: r0811509/mobile-beer
  ports:
    - 8051:8051
  links:
    - mysql
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql
   
 edge-service:
  depends_on:
    - beer-service
    - user-service
    - consumption-service
  image: r0811509/mobile-edge
  ports:
    - 8053:8053

 
volumes:
 mongodb_data_container:
 mongodb_data_container2:
 mysql_data_container:
